# Generated by Django 2.1.4 on 2019-01-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=15)),
                ('secret', models.CharField(max_length=15)),
                ('server', models.CharField(max_length=4)),
                ('farm', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('is_public', models.BooleanField()),
                ('is_friend', models.BooleanField()),
                ('is_family', models.BooleanField()),
                ('date_added', models.CharField(max_length=20)),
                ('ownername', models.CharField(max_length=20)),
            ],
        ),
    ]
