# Generated by Django 2.1.4 on 2019-01-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FGroup',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FPhoto',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=15)),
                ('secret', models.CharField(max_length=15)),
                ('server', models.CharField(max_length=4)),
                ('farm', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('ispublic', models.IntegerField()),
                ('isfriend', models.IntegerField()),
                ('isfamily', models.IntegerField()),
                ('ownername', models.CharField(max_length=20)),
                ('dateadded', models.CharField(max_length=15)),
                ('group', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FUser',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('ownername', models.CharField(max_length=20, unique=True)),
                ('group', models.ManyToManyField(to='flickrdb.FGroup')),
            ],
        ),
    ]
