# Generated by Django 2.1.4 on 2019-01-09 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('flickrdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='is_family',
            new_name='isfamily',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='is_friend',
            new_name='isfriend',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='is_public',
            new_name='ispublic',
        ),
    ]
