# Generated by Django 2.1.4 on 2019-01-09 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('flickrdb', '0002_auto_20190109_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='date_added',
            new_name='dateadded',
        ),
    ]
