# Generated by Django 2.1.4 on 2019-01-11 19:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flickrdb', '0002_auto_20190111_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuser',
            name='group',
        ),
        migrations.AddField(
            model_name='fuser',
            name='group',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='flickrdb.FGroup'),
            preserve_default=False,
        ),
    ]
