# Generated by Django 2.1.4 on 2019-01-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flickrdb', '0003_auto_20190111_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuser',
            name='group',
        ),
    ]
