# Generated by Django 2.1.5 on 2019-01-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flickrdb', '0004_remove_fuser_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='fgroup',
            name='groupname',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='fgroup',
            name='noofphotos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fgroup',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
